### ISSUE TITLE
"Others" Equipment not found

### ISSUE THREAD

**Issue by MateoGreil** [fmartinou/tydom2mqtt#108]
Hi,

firstly, that's an awesome integration in HA, and thanks for that !

My query is about the "Others" Equipements.
In the Tydom app, I've added equipments in "Others" / "Autres" in french, and I can't find it in the HA list of my equipments.
Is it known ? Is it wanted ?

Thanks for your reply !
And again, nice job !

**Comment by Neo33ASM** [comment]
J'ai regardé le code et ce n'est pas pris en charge en effet, c'est juste que :
- soit le codeur n'a jamais rencontré ce cas de figure
- soit personne ne lui a demandé

J'ai également un équipement dans "autres", je suis en train de coder une proposition de mise à jour, il n'y aura plus qu'à espérer que @fmartinou la vérifie/intègre dès qu'il le pourra.

**Comment by MateoGreil** [comment]
Je comptais m'en occupé mais si tu as déjà commencé alors c'est parfait !
Aussi, ca ne me concerne pas parce que j'en ai pas, mais je pense qu'il manque un paquet d'autres choses. "Je pense" parce que je ne suis pas certain d'etre aller assez en profondeur dans le code, mais apres un coup d'oeil, je ne vois que 6 sensors, alorsq que sur l'app tydom, j'en vois 13.

**Comment by Neo33ASM** [comment]
@MateoGreil je viens de push une merge request : [https://github.com/fmartinou/tydom2mqtt/pull/109](url)

J'ai des modules de volets roulants que j'ai catégorisés en "stores" qui ne sont donc pas pris en compte (simple renaming), mais pour les "others", à ce jour je n'ai que des modules on/off moi.

En majorité les modules acceptés dans cette section sont de ce genre, mais j'ai vu qu'il est possible d'y mettre un Tyxia 6410 dans cette catégorie. J'en ai un mais je n'ai pas encore fait le test.

Actuellement, seul le "lastUsage" est utilisé pour déterminer la catégorie du device, pour avoir une détermination plus fine, il faudra intégrer le parsing de la signature de celui-ci, voici un morceau de code de [https://github.com/mgcrea/homebridge-tydom](url)

`const ENDPOINTS_SIGNATURES_CATEGORIES: Record<string, Categories | [Categories, Record<string, unknown>]> = {
  'alarm:0c6e1d33808fa50a0a921502f80d36430dfaeda5abfed2467f9f2b07821e4842': Categories.SECURITY_SYSTEM, // @maaxleop
  'alarm:6e33f7ee5e62b58f4e888c91a13fd9b9d868f3751cead5ea1252578ba86523a5': [
    Categories.SECURITY_SYSTEM,
    {legacy: true}
  ], // @StephanH27.1521931577 (CTX60) #50
  'alarm:aad768ee0367013a974276117fd5ed4834cc26e4d31acc88d35134731331b0e7': Categories.SECURITY_SYSTEM, // @mgcrea.1521931577 (TYXAL+)
  'awning:48f43ebab20eba438fa9cc2b6ce44311d3cfb01c5be84bf17599d9c152c348d3': Categories.WINDOW_COVERING, // @baschte_(TYXIA 5731)
  'belmDoor:fb935867933d89b3058f09384f76fd63f3defb18cfb3172f60fa9f4f237f748b': Categories.DOOR, // @mgcrea (MDO)
  'conso:16804a9994bce28275150db329a9c0b931ef7f20608c1a3d2ff248f58569f0d3': Categories.SENSOR, // @maaxleop (STE 2000)
  'garage_door:83b0912c6fe14622219522922ea0347dcbf86bf9cfd3346a2eca8eac70ca8260': Categories.GARAGE_DOOR_OPENER, // @Benzoiiit (TYXIA 4620)
  'gate:83b0912c6fe14622219522922ea0347dcbf86bf9cfd3346a2eca8eac70ca8260': Categories.GARAGE_DOOR_OPENER, // @mgcrea (TYXIA 4620)
  'hvac:16804a9994bce28275150db329a9c0b931ef7f20608c1a3d2ff248f58569f0d3': Categories.SENSOR, // @D-Roch+@tanabay27 (Sonde TYBOX 2020 Wt)
  'hvac:17f933bec8ed29f9b2a2cd5280fb5b64806cf8a1c064c83950e350f491d7cb9f': Categories.THERMOSTAT, // @Armen85 (RF6600FP) @FIXME
  'hvac:1bab47d1dd7e898b5dc2e9867b14dfb8bc9272c4cb0b5d1221da962d43a6ffb4': Categories.THERMOSTAT, // @mgcrea (RF4890)
  'light:449e2a60377094cde10224cee91d378fb0ae373ae6ceea0ac2cbc1ed011bffa7': Categories.LIGHTBULB, // @mgcrea (TYXIA 5610, TYXIA 6610)
  'light:fce45085835f4f2790ea3b17d208b5ace34935444d2535e75ba3f0a2ce86de5f': Categories.LIGHTBULB, // @mgcrea (TYXIA 5650)
  'others:449e2a60377094cde10224cee91d378fb0ae373ae6ceea0ac2cbc1ed011bffa7': Categories.LIGHTBULB, // @diegomarino (TYXIA 4600)
  'plug:2534c497ff8fb013a88da28d341adff5bc0ba77e1fc8ea8dcb8b8f1c9d62ce19': Categories.OUTLET, // @Neo33ASM (Easy Plug)
  'shutter:c3fe8e2afa864e1a7a5c6676b4287a7b2f2a886a466baec3df8a1ec4f898ad6c': Categories.WINDOW_COVERING, // @maaxleop
  'window:fb935867933d89b3058f09384f76fd63f3defb18cfb3172f60fa9f4f237f748b': Categories.WINDOW, // @mgcrea (MDO)
  'sensor:556f8aaf51e3807397b7e326d0aad4b61cceb8279166b50204f8a2e95464c9ba': [Categories.SENSOR, {smokeDetector: true}] // DFR TYXAL+
};`

**Comment by Neo33ASM** [comment]
@MateoGreil je viens de push une merge request : [https://github.com/fmartinou/tydom2mqtt/pull/109](url)

Si @fmartinou peut y jeter un coup d'œil et donner son avis dès qu'il le pourra ça serait cool :)

J'ai des modules de volets roulants que j'ai catégorisés en "stores" qui ne sont donc pas pris en compte (simple renaming), mais pour les "others", à ce jour je n'ai que des modules on/off moi.

En majorité les modules acceptés dans cette section sont de ce genre, mais j'ai vu qu'il est possible d'y mettre un Tyxia 6410 dans cette catégorie. J'en ai un mais je n'ai pas encore fait le test.

Actuellement, seul le "lastUsage" est utilisé pour déterminer la catégorie du device, pour avoir une détermination plus fine, il faudra intégrer le parsing de la signature de celui-ci, voici un morceau de code de [https://github.com/mgcrea/homebridge-tydom](url)

![image](https://github.com/fmartinou/tydom2mqtt/assets/49551827/dd6345ce-e304-42b8-9dfc-dcbaef282198)

**Comment by Neo33ASM** [comment]
D'ailleurs je lui avait fait intégrer (à mgcrea sur homebridge) les nouveau plugs [https://www.deltadore.fr/domotique/pilotage-eclairage/eclairages-connectes/easy-plug-e16em-ref-6353005](url).
On peut le voir dans la liste du screen ci-dessus. Mais il faudra visiblement créer une nouvelle catégorie.

**Comment by MateoGreil** [comment]
En attendant que @fmartinou on n'a pas moyen de le faire au travers de ton repo ?

**Comment by Neo33ASM** [comment]
Pour les awnings c'est ok, pour le other je pense que non, je vérifie pourquoi

**Comment by Neo33ASM** [comment]
@fmartinou pour les volets classés en "awnings" c'est ok ça fonctionne, mais pour others j'ai visiblement oublié le 's', c'est 'others' et non 'other', du coup je viens de pull une nouvelle merge request (#110)

**Comment by fmartinou** [comment]
Merci @Neo33ASM ,

C'est mergé ; je vais releaser pour que tout le monde puisse profiter de ces dernières features 👍

**Comment by fmartinou** [comment]
Released as `3.2.0`
(set as addon latest version in HASS.io)
