### ISSUE TITLE
History graphs no longer uodate after a few hours (need to restart tydom2mqtt to fix)

### ISSUE THREAD

**Issue by Sleinous** [fmartinou/tydom2mqtt#113]
Every few hours the logger for my delta dore temperature graphs hangs as a straight line with no more data received.
The logs in tydom2mqtt show thus : 2023-07-19 05:00:51,102 - __main__ - WARNING - Unable to handle message: no close frame received or sent

Any ideas where this is coming from?
Thanks
Jon

**Comment by fmartinou** [comment]
It's likely the same issue as #107; I close is as duplicated.

In the meantime, a `3.3.0` version has just been released and contains an attempt to fix it; if you can give it a try 🤞 .
