### ISSUE TITLE
Gestion de l’énergie dans Home Assistant

### ISSUE THREAD

**Issue by milouze03400** [fmartinou/tydom2mqtt#13]
Bonjour tydom2mqtt fonctionne très bien !!!, sauf qu'il est impossible de l'intégrer dans le gestion de l'énergie de home assistance les sensors ne sont pas répertoriées avez-vous une idée du problème cordialement

**Comment by fmartinou** [comment]
Bonjour,

Pour que les entités soient compatibles avec le module de gestion de l'énergie de HA, il faut en amont  qu'elles soient compatibles avec la fonctionnalité de [long-term statistics](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics)

Ca se passe en donnant aux entités à minima une `state_class` de type `measurement`, `total` ou `total_increasing` en fonction du type d'appareil.

Je ne sais pas s'il est possible de définir ces propriétés à partir des informations récupérées via la Tydom lors de la découverte des capteurs 🤔 ?

**Comment by milouze03400** [comment]
Bonsoir merci pour ta réponse j'ai essayé l'intégration Utility meter et là j'arrive à l'intégrer à la gestion de  l'énergie de HA mais les  remontées de consommation son incohérents  car les remonter des capteurs tydom sont en W ou en Wh il faudrait qu'il soit en kWh par contre les remontée de production solaire  (ECU Aps) sont juste. Sachant que je suis nouveau sur HA cela reste compliquer pour moi cordialement

**Comment by fmartinou** [comment]
Pour passer d'une consommation instantanée (en W par ex) vers une consommation en KWh, il faut généralement utiliser l'intégration [`Riemann sum integral`](https://www.home-assistant.io/integrations/integration/).

Exemple
```
sensor:
  - platform: integration
    source: sensor.current_power
    name: energy_spent
    unit_prefix: k
    round: 2
```

**Comment by milouze03400** [comment]
Bonjour
super merci  pour ta réponse ça fonctionne parfaitement
