### ISSUE TITLE
tyxia 5610 compatibility ?

### ISSUE THREAD

**Issue by herbalizer404** [fmartinou/tydom2mqtt#15]
Hi

I would like to connect a second hand tydom 1.0 to home assistant to control tyxia 5610 lights and related wireless switches.

Do tout know if this hardware will work and be available and controllable in HA?

Thank you for your work

**Comment by fmartinou** [comment]
Hi,

I think so.

If these devices are X2D/X3D and that Deltadore mentioned them as compatible with a Tydom 1.0, it should work.

> to connect a second hand tydom 1.0

Be also informed that the initial setup to get the 'tydom password' will be a little tricky [as mentioned here](https://fmartinou.github.io/tydom2mqtt/#/faq/?id=how-to-reset-my-tydom-password) (downloading an old deltadore app, etc.)

**Comment by herbalizer404** [comment]
Great, thank you. It will save me to change all lights and switches installed by my home builder.
