### ISSUE TITLE
I can't access to my tydom

### ISSUE THREAD

**Issue by agarridosaez** [fmartinou/tydom2mqtt#16]
Hello,

Thank you very much for your great effort.

I've been with home Assitant for a one year and the only thing I haven't been able to integrate is Tydom. It's very frustrating.

To integrate tydom in home assistant there are 2 pieces, the mosquitto broker and the tydom2mqtt.

I don't know which one is failing. I'll pass you the configuration of my tydom2mqtt and the log to see if it helps.

In red the altered values ​​but that are good

Thanks a lot

![image](https://user-images.githubusercontent.com/5555882/152880856-d481fade-88e8-4c29-b7fc-185a67bcb48d.png)

![image](https://user-images.githubusercontent.com/5555882/152880916-8ccf91a0-19ed-4bbe-a4de-6af612fd52cc.png)

**Comment by fmartinou** [comment]
Hi,

Thank you for your support.

I think you got 2 errors.

**The 1st one `Parsing error TYDOM_ALARM_PIN`**
Even if you don't have any alarm, please set an arbitrary value (eg `123456`)

It's an issue I need to resolve (see #12)

**The 2nd one is related to `MQTT connection error ... (127.0.0..1, 1883)`**
Please notice that the addon is not running on the docker `host` network so the MQTT host is likely to be different from localhost|127.0.0.1

**Comment by agarridosaez** [comment]
Hello,
Thank you very much for your quick response.
I have solved the 2 problems thanks to your help and I already have Tydom working on my hassio.
Great work of yours......
