### ISSUE TITLE
1 seul volet non reconnu sur 16

### ISSUE THREAD

**Issue by Leonzarea** [fmartinou/tydom2mqtt#174]
Bonjour,

J'ai 16 volets roulants sur ma tydom v1 qui sont tous fonctionnels via l'application.
Mais dans tydom2mqtt, il n'y en a que 15 de visibles...

J'ai ceci dans la log qui pourrait expliquer le volet manquant : 
2024-02-10 10:11:47,423 - tydom.MessageHandler - WARNING - Unknown device name (1647262788_1647262788)
2024-02-10 10:11:47,423 - tydom.MessageHandler - WARNING - Unknown device type (1647262788_1647262788)
2024-02-10 10:11:47,453 - tydom.MessageHandler - WARNING - Unknown message type received ([]

Les volets ont tous été installés en meme temps donc cerainement tous le meme modele.
Une idée de comment debugguer plus loin ?

Merci.

**Comment by BlacKTM1190** [comment]
Hello,

Les volets n'ont pas été touchés depuis un moment mais peux-tu nous fournir la release utilisée ?
Peux-tu fournir ces mêmes logs mais en LOG_LEVEL="DEBUG" si ils sont plus verbeux ?
Quand tu manoeuvre le volet en question depuis l'app Tydom, vois-tu des choses passer dans les logs et/ou sur mqtt explorer ?

**Comment by BlacKTM1190** [comment]
Hello,
Effectivement, pas grand chose de plus...
Depuis l'app tydom, dans `Menu burger / Ton domicile / Informations / Installation`, l'équipement en question est-il bien dans le métier volet ?
Le cas écheant, il faut le ré-associer.
D'ailleurs, même s'il est dans le métier shutter, cela vaudrait le coup de le ré-associer.
Cependant, il va te falloir "ouvrir" la sous-face de la menuiserie ou l'appéreillage de la commande filaire, pour connaître le modèle (Tyxia 4630, 5630, ou moteur well'com, eveno...) car à ma connaissance l'app ne te le permet pas mais te le demande lors de l'ajout d'un équipement.

**Comment by Leonzarea** [comment]
Hello,

Après vérification dans l'app tydom, cet équipement était en métier "Volet Battant", contrairement aux autres qui étaient en "volet".
Je l'ai supprimé puis réassocié en volet tout simple (Well'com) et il est maintenant visible dans HA.

Merci beaucoup pour l'aide, mon problème est résolu :-)
Surement une fausse manip lorsque l'on a associé l'ensemble des volets à la box.
