### ISSUE TITLE
Tydom2Mqtt home assistant http 401 error

### ISSUE THREAD

**Issue by Aurel-rpi** [fmartinou/tydom2mqtt#175]
Hello , 

First of all, thank you for your work.

I am writing because I need your help. I configured the tydom2mqtt extension and the connection is made correctly with my Tydom 1.0 box. I see in the logs that my calybox is found but no device appears in the mqtt integration as if no device was created by tydom2mqtt.

I have this error before establishing the connection
"Error 401 authentication requested"

I can clearly see the connection in mosquitto

Can you help me identify the problem?

Thanks  😃 

[LogTydom2mqtt.txt](https://github.com/fmartinou/tydom2mqtt/files/14310794/LogTydom2mqtt.txt)

**Comment by BlacKTM1190** [comment]
Hello
Do you use the latest release ?
The polling have been restored in 3.4.3 for such devices.
I'm not on this release yet but will try to upgrade this w-e, looking for my Tywatt and give my feedback.
Another question : I see in your logs that you have set an alarm pin, is your alarm working through HA ?

**Comment by Aurel-rpi** [comment]
Yes my installation actually runs the 3.4.3 release and i can see the polling in log file.
I'm interested in your feedback on this version. It seems to me that I also have a tywatt on my electrical panel but I haven't paired it yet.
No I don't have an alarm working through HA, I filled in this field because I saw on forums that some users had problems leaving it empty

**Comment by fmartinou** [comment]
Hi,

That's an authentication issue to the Tydom; the credentials used must be invalid.

It's a often a pain to get these credentials.

Please see:
- [the FAQ](https://fmartinou.github.io/tydom2mqtt/#/faq/?id=how-to-reset-my-tydom-password)
- [the home-assistant integration howto](https://fmartinou.github.io/tydom2mqtt/#/hass/)
- [this tuto to get them](https://community.home-assistant.io/t/integrating-new-2023-tydom-deltadore-x3d-zigbee-gateway-with-home-assistant-solved/537503)

**Comment by neilerua973** [comment]
It works well for me after resetting the password of my tydom, by pressing the button during 15sec.
