### ISSUE TITLE
External temp sensor

### ISSUE THREAD

**Issue by WeftWiki** [fmartinou/tydom2mqtt#19]
I have a external temperature sensor directly connected to the Tydom box (without any Calybox). The sensor is shown in the Tydom app, but no entity is created in Home Assistant.

**Comment by BlacKTM1190** [comment]
Hello
Could you tell us the reference ?

**Comment by WeftWiki** [comment]
This is this sensor: https://www.deltadore.fr/domotique/gestion-chauffage/accessoires/sonde-exterieure-radio-ref-6300036

**Comment by WeftWiki** [comment]
I found out how my sensor is listed:

>  {
>         "id_endpoint": 1647600390,
>         "first_usage": "conso",
>         "skill": "TYDOM_X3D",
>         "id_device": 1647600390,
>         "name": "Temps Mod Pool",
>         "anticipation_start": false,
>         "picto": "default_device",
>         "last_usage": "conso"
>       }

This kind of temperature sensor is not listed in conso device classes
