### ISSUE TITLE
HVAC_Action in coooling Mod

### ISSUE THREAD

**Issue by dmorvant56** [fmartinou/tydom2mqtt#194]
When we are in cooling mode, the system cooled as long as the current temperature is higher than the target temperature and not the reverse :

![image](https://github.com/fmartinou/tydom2mqtt/assets/113779559/d1c8c6b4-dc48-4c12-8ffc-5227798f9a08)

**Comment by fmartinou** [comment]
Hi,

It has been fixed: https://github.com/fmartinou/tydom2mqtt/pull/195
