### ISSUE TITLE
alarm code cannot start with zero 0

### ISSUE THREAD

**Issue by papo-o** [fmartinou/tydom2mqtt#2]
Hello,
in configuration page it's impossible to set a alarm code if it start with a zero

**Comment by fmartinou** [comment]
Hi,

I guess your request is about the hass.io addon.

The configuration page expected an integer, that's probably why you couldn't set a pin starting with `0`.
[I just changed it to a `string`](https://github.com/fmartinou/hassio-addons/commit/cff8ab7ef5cd3de0bdd5f68e91447dc25d7d9988); could you retry please? (you probably need to refresh the hass.io repository on Home-Assistant first).

**Comment by papo-o** [comment]
it work fine
thanks
