### ISSUE TITLE
Dockerhub tag latest

### ISSUE THREAD

**Issue by MateoGreil** [fmartinou/tydom2mqtt#221]
Hello!

I have gotten into the habit of using the tag `latest` on my Docker containers and pulling updates from time to time without bothering to check for new versions. But your tag `latest` is not the latest version on DockerHub.

It's not a big deal at all, I manually set it to 3.5.3, but just wanted to let you know in case it was unintentional ;)

Have a great day!

**Comment by fmartinou** [comment]
Hi,

Thanks you for your feedback 👍 

The `latest` tag represents the last version built from the `main` branch whereas the `x.y.z` tags are built from their respective git tags.
So it doesn't surprise me that both are different on the Hub ; I'll double check just to confirm that there is not something __deeper__. 😃
