### ISSUE TITLE
Error 401 from tydom mediation

### ISSUE THREAD

**Issue by maverick62** [fmartinou/tydom2mqtt#24]
Hello,

I am new user of tydom 1.0.

I use your app with docker but i have a problem.

The connexion with MQTT is OK but just after, when it tries to connect to the tydom 1.0 i have an 401 error.

I am sure of the password cause i just entered it on the tydom.

I can"t connect with a browser, user = mac address and password : tydom password.

Is it an update?

Thanks

**Comment by fmartinou** [comment]
Hi,

Have you read [this part of the documentation?](https://fmartinou.github.io/tydom2mqtt/#/faq/?id=how-to-reset-my-tydom-password)


The password needed here is not the same as the password you're using on the Tydom app.
It' already been discussed [here](https://github.com/fmartinou/tydom2mqtt/issues/6), [here](https://github.com/fmartinou/tydom2mqtt/issues/5), [here](https://github.com/mrwiwi/tydom2mqtt/issues/38), [here](https://github.com/mrwiwi/tydom2mqtt/issues/38), [here](https://github.com/mrwiwi/tydom2mqtt/issues/21) and [here](https://github.com/mrwiwi/tydom2mqtt/issues/14) 😀 

You likely need to install an old Tydom app version to be able to set/reset the tydom hardware appliance password.

**Comment by maverick62** [comment]
ah d'accord,

j'essaie cet aprés midi et je vous redis quoi.

Merci pour la réponse

**Comment by maverick62** [comment]
tout fonctionne,
Merci beaucoup
