### ISSUE TITLE
Binary sensors created but not updated

### ISSUE THREAD

**Issue by LGO44** [fmartinou/tydom2mqtt#28]
Here is an extract of the log from the tydom2MQTT
 FR : Extrait du fichier journal de tydom2MQTT

_2022-07-27 22:53:16,812 - sensors - INFO - Sensor created / updated : device_id_tydom__Chambre_1 1651773567
2022-07-27 22:53:16,815 - sensors - INFO - Sensor created / updated : endpoint_id_tydom__Chambre_1 1651773567
2022-07-27 22:53:16,816 - sensors - INFO - Sensor created / updated : id_tydom__Chambre_1 1651773567_1651773567
2022-07-27 22:53:16,818 - sensors - INFO - Binary sensor created / updated : thermicDefect_tydom__Chambre_1 False
2022-07-27 22:53:16,820 - sensors - INFO - Sensor created / updated : position_tydom__Chambre_1 0
2022-07-27 22:53:16,822 - sensors - INFO - Binary sensor created / updated : onFavPos_tydom__Chambre_1 False
2022-07-27 22:53:16,824 - sensors - INFO - Binary sensor created / updated : obstacleDefect_tydom__Chambre_1 False
2022-07-27 22:53:16,826 - sensors - INFO - Binary sensor created / updated : intrusion_tydom__Chambre_1 False
2022-07-27 22:53:16,827 - sensors - INFO - Binary sensor created / updated : battDefect_tydom__Chambre_1 False
2022-07-27 22:53:16,829 - cover - INFO - Cover created / updated : Chambre 1 1651773567_1651773567 0_

But the states are not updated
FR:Les état des variables créées ne sont pas mis à jour

![image](https://user-images.githubusercontent.com/95585425/181376788-c0a87b5c-05aa-4d38-aecf-d245caaba713.png)

je pense qu'il s'agit d'un problème de décodage de la réponse json .

Merci pour votre aide

**Comment by LGO44** [comment]
Il ne s'agit pas vraiment d'un problème de décodage de la réponse json mais d'un problème de payload :
 un binary sensor attend un payload_on "On" et  un payload_off "Off" hors la réponse est "True" et "False" donc j'ai rajouté dans le fichier configuration.yaml des binary_sensors

mqtt:
 - binary_sensor
 '# Volet Cuisine
    - name: DefautBatterie_Volet_tydom_Cuisine
      state_topic: "binary_sensor/tydom/battDefect_tydom_1651782167_1651782167/state"
      **payload_on: "True"
      payload_off: "False"**
      device_class: battery

    - name: "defautThermique_Volet_tydom_Cuisine"
      state_topic: "binary_sensor/tydom/thermicDefect_tydom_1651782167_1651782167/state"
      **payload_on: "True"
      payload_off: "False"**
      qos: 0
      device_class: problem    
      
    - name: "intrusion_Volet_tydom_Cuisine"
      state_topic: "binary_sensor/tydom/intrusion_tydom_1651782167_1651782167/state"
      **payload_on: "True"
      payload_off: "False"**
      qos: 0
      device_class: problem
      
    - name: "defautObstacle_Volet_tydom_Cuisine"
      state_topic: "binary_sensor/tydom/obstacleDefect_tydom_1651782167_1651782167/state"
      **payload_on: "True"
      payload_off: "False"**
      qos: 0
      device_class: problem
                 
    - name: "onFavPos_Volet_tydom_Cuisine"
      state_topic: "binary_sensor/tydom/onFavPos_tydom_1651782167_1651782167/state"
      **payload_on: "True"
      payload_off: "False"**
      qos: 0
      device_class: problem

@fmartinou Peut-on reporter cette correction dans l'intégration? 

![image](https://user-images.githubusercontent.com/95585425/188021111-e824f2de-5861-427a-818c-20b093b9e1c3.png)

**Comment by LGO44** [comment]
@fmartinou 

Je pense que l'on peut résoudre ce bug par la modification de la ligne 54 du fichier sensor.py en ajoutant "True","False" ou modifiant de la même façon "true", "false"

        self.config_topic = sensor_config_topic.format(id=self.id)
        if 'unit_of_measurement' not in tydom_attributes_payload.keys() and (self.elem_value in ["0", "1", "true", "false"]or type(self.elem_value) == bool):
            self.binary = True
            self.json_attributes_topic = binary_sensor_json_attributes_topic.format(
                id=self.id)
            self.config_topic = binary_sensor_config_topic.format(id=self.id)
            # if 'efect' in self.elem_name:
            #     self.device_class = 'problem'
            # elif 'ntrusion' in self.elem_name or 'zone' in self.elem_name or 'alarm' in self.elem_name:
            #     self.device_class = 'safety'
            # elif 'gsm' in self.elem_name:
            #     self.device_class = 'signal_strength'
        else:
            self.json_attributes_topic = sensor_json_attributes_topic.format(
                id=self.id)
            self.config_topic = sensor_config_topic.format(id=self.id)
            # if 'emperature' in self.elem_name:
            #     self.device_class = 'temperature'

**Modification proposée** 
if 'unit_of_measurement' not in tydom_attributes_payload.keys() and (self.elem_value in ["0", "1", "true", "false","True","False"] or type(self.elem_value) == bool):
            self.binary = True

EN:
I think that we can fix this issue by modifying the line 54 of the file sensor.py of the application by either adding 

        self.config_topic = sensor_config_topic.format(id=self.id)
        if 'unit_of_measurement' not in tydom_attributes_payload.keys() and (self.elem_value in ["0", "1", "true", "false"]or type(self.elem_value) == bool):
            self.binary = True
            self.json_attributes_topic = binary_sensor_json_attributes_topic.format(
                id=self.id)
            self.config_topic = binary_sensor_config_topic.format(id=self.id)
            # if 'efect' in self.elem_name:
            #     self.device_class = 'problem'
            # elif 'ntrusion' in self.elem_name or 'zone' in self.elem_name or 'alarm' in self.elem_name:
            #     self.device_class = 'safety'
            # elif 'gsm' in self.elem_name:
            #     self.device_class = 'signal_strength'
        else:
            self.json_attributes_topic = sensor_json_attributes_topic.format(
                id=self.id)
            self.config_topic = sensor_config_topic.format(id=self.id)
            # if 'emperature' in self.elem_name:
            #     self.device_class = 'temperature'

**Modification proposed:** 
if 'unit_of_measurement' not in tydom_attributes_payload.keys() and (self.elem_value in ["0", "1", "true", "false","True","False"] or type(self.elem_value) == bool):
            self.binary = True

**Comment by fmartinou** [comment]
@LGO44 Thanks for the analysis and the proposal; [I changed the code  as proposed](https://github.com/fmartinou/tydom2mqtt/blob/master/app/sensors.py#L54-L64).

It will be part of the next release.

**Comment by fmartinou** [comment]
`2.3.0` is out.
