### ISSUE TITLE
New Tydom Home 2022 product and Password

### ISSUE THREAD

**Issue by Marcoparigi** [fmartinou/tydom2mqtt#30]
Hi,
how can we do this with the new Tydom Home product ?
I don't know how to change/reset hardware password and don't know even if exists !? :(

Hi,

Have you read [this part of the documentation?](https://fmartinou.github.io/tydom2mqtt/#/faq/?id=how-to-reset-my-tydom-password)

The password needed here is not the same as the password you're using on the Tydom app.
It' already been discussed [here](https://github.com/fmartinou/tydom2mqtt/issues/6), [here](https://github.com/fmartinou/tydom2mqtt/issues/5), [here](https://github.com/mrwiwi/tydom2mqtt/issues/38), [here](https://github.com/mrwiwi/tydom2mqtt/issues/38), [here](https://github.com/mrwiwi/tydom2mqtt/issues/21) and [here](https://github.com/mrwiwi/tydom2mqtt/issues/14) 😀 

You likely need to install an old Tydom app version to be able to set/reset the tydom hardware appliance password.

_Originally posted by @fmartinou in https://github.com/fmartinou/tydom2mqtt/issues/24#issuecomment-1133852869_

**Comment by BlacKTM1190** [comment]
Hello
I don't know the new Tydom Home but it seems that there is a button at the back "H" :
![image](https://user-images.githubusercontent.com/58290651/183627875-8359e229-ab30-463c-afc5-0f0b0c83c8e7.png)
![image](https://user-images.githubusercontent.com/58290651/183628072-98555dc5-8d22-4254-9e84-643ecb590d95.png)
With Tydom 1.0, we can also use K-Line App to reset the box password.

**Comment by Marcoparigi** [comment]
Thanks for info, but maybe we can try to see password with sniffer or proxy ?
Does anyone know how to do that ?

**Comment by Marcoparigi** [comment]
Problem solved.
Download apk version 3+ of Tydom app. (From aptoide)( if you use mac you can do it within BlueStacks emulator)
Then launch the app. Try with a wrong password. A message appear telling you to press 15sec the reset button of your tydom home.
Next it will prompt you to set the new password of your choice.

All done !
