### ISSUE TITLE
Support for sunshade cover

### ISSUE THREAD

**Issue by erichard** [fmartinou/tydom2mqtt#31]
Sunshades can be opened and closed like cover but they also can be oriented ([example](https://static.k-line.fr/public/styles/produit_slider_image_first_desk/public/2021-11/brise-soleil-lames-vue-interieure-k-line.jpg?VersionId=vg3gk.6Xsti8_w4ffN3TJfPRxFAe.E5A&itok=4emJMmqn))

How can we add support for this ?

**Comment by fmartinou** [comment]
Thank you very much for the PR 👍 .
It's merged and it will be part of the next release.

**Comment by fmartinou** [comment]
`2.3.0` is out.
