### ISSUE TITLE
Unable to collect alarm event / Impossible de collecter l'évènement de l'alarme

### ISSUE THREAD

**Issue by nicolas2k** [fmartinou/tydom2mqtt#32]
FRA: Malgré des infructueux de recherche en reverse engineering de APK version 4.xx, mon bur est de pouvoir collecter les différents évènements de l'alarme comme défaut pile, autoprotection ouverture d'issue, alarme déclenché, etc... qu'on pouvait consulter depuis mobile, mais c'est hyper lourd et hyper lent lorsqu'on a pas mal d'entrée.

Connaisseriez-vous une commande équivaut de ce type "GET /devices/{deviceId}/endpoints/{deviceId}" ou autre url qui permet d'interroger les events ? Cela me servira des suivies et des préventifs pour changer des piles.

J'utilise le TYDOM-1 et Delta Pack4...

Merci

ENG : Despite unsuccessful research in reverse engineering of APK on version 4.xx, my goal is to be able to collect some events of the alarm such as battery failure, autoprotection, opening of an issue, alarm triggered, etc... which we could consult from mobile, but it's very heavy and very slow when you have a lot of input.

Do you know an equivalent command of this type "GET /devices/{deviceId}/endpoints/{deviceId}" or other url that allows you to query the events ? This will be to use as follow-ups and preventives for changing batteries.

I use the TYDOM-1 and Delta Pack4...

Thanks

**Comment by nicolas2k** [comment]
FRA: Malgré des infructueux de recherche en reverse engineering de APK version 4.xx, mon bur est de pouvoir collecter les différents évènements de l'alarme comme défaut pile, autoprotection ouverture d'issue, alarme déclenché, etc... qu'on pouvait consulter depuis mobile, mais c'est hyper lourd et hyper lent lorsqu'on a pas mal d'entrée.

Connaisseriez-vous une commande équivaut de ce type "GET /devices/{deviceId}/endpoints/{deviceId}" ou autre url qui permet d'interroger les events ? Cela me servira des suivies et des préventifs pour changer des piles.

J'utilise le TYDOM-1 et Delta Pack4...

Merci

ENG : Despite unsuccessful research in reverse engineering of APK on version 4.xx, my goal is to be able to collect some events of the alarm such as battery failure, autoprotection, opening of an issue, alarm triggered, etc... which we could consult from mobile, but it's very heavy and very slow when you have a lot of input.

Do you know an equivalent command of this type "GET /devices/{deviceId}/endpoints/{deviceId}" or other url that allows you to query the events ? This will be to use as follow-ups and preventives for changing batteries.

I use the TYDOM-1 and Delta Pack4...

Thanks

**Comment by nicolas2k** [comment]
With exploration, I found little more infos but not enough for me, so I know, it's possible collect event from Alarm Histo see keyword histo and EVENTS with command :

GET /devices/{deviceId}/endpoints/{deviceId}/cmeta
 
{
    "id": 1515151515,
    "error": 0,
    "cmetadata": [
        {
            "name": "partCmd",
            "permission": "w",
            "parameters": [
                {
                    "name": "value",
                    "type": "string",
                    "enum_values": [
                        "OFF",
                        "ON",
                        "FORCED_ON"
                    ]
                },
                {
                    "name": "part",
                    "type": "numeric",
                    "min": 1,
                    "max": 4
                }
            ]
        },
        {
            "name": "histo",
            "permission": "r",
            "parameters": [
                {
                    "name": "type",
                    "type": "string",
                    "enum_values": [
                        "OPEN_ISSUES",
                        "UNACKED_EVENTS",
                        "ON_OFF",
                        "EVENTS"
                    ]
                },
                {
                    "name": "indexStart",
                    "type": "numeric",
                    "min": 0,
                    "max": 1023
                },
                {
                    "name": "nbElem",
                    "type": "numeric",
                    "min": 1,
                    "max": 1024
                }
            ]
        }
    ]
}

And, I try to use with PUT /devices/{}/endpoints/{}/cdata?name=histo, with body = '{"value": "EVENTS", "pwd": "5555"}'
it saids error http 500 ...
I did not find my mistake

**Comment by mopi1402** [comment]
Hello,
je pense que le boulot a déjà été fait par fransiouz.
Pull Request en attente de validation ;)

https://github.com/fmartinou/tydom2mqtt/pull/44

**Comment by fmartinou** [comment]
Released as `2.5.0`
