### ISSUE TITLE
Deploy the tydom2mqtt docker image by yourself missing link home assistant

### ISSUE THREAD

**Issue by moi952** [fmartinou/tydom2mqtt#4]
Hello,
there is no link for configuration for home assistant via docker.
is the documentation provided?

Thank you

**Comment by fmartinou** [comment]
Hi,

In the Github project, the README is pointing [to the documentation](https://fmartinou.github.io/tydom2mqtt/#/).
Didn't you find it?
Or maybe did I misunderstand your question?

**Comment by moi952** [comment]
There is indeed a category, but unfortunately the link points to "https://fmartinou.github.io/tydom2mqtt/#/../introduction/" which gives me a 404

**Comment by fmartinou** [comment]
Could you tell me where you've found the wrong link so I fix it?

**Comment by moi952** [comment]
Here : https://fmartinou.github.io/tydom2mqtt/#/hass/

Solution 1 : Deploy the tydom2mqtt docker image by yourself (see here)

Thanks :-)

**Comment by fmartinou** [comment]
Ok thanks!
It's now fixed 😄
