### ISSUE TITLE
I haven't been able to access my tydom from Home Assistant for months

### ISSUE THREAD

**Issue by agarridosaez** [fmartinou/tydom2mqtt#58]
Hi folks,

I have 1 1/2 year experience with Home Assistant. And some time ago I was able to install the tydom2mqtt addon.

I had to reinstall all my home assistant and the only thing I couldn't get back was my Tydom.

I've been with this for months and it doesn't freak me out. I am asking for some help please.....

This is the error the log gives me:

![image](https://user-images.githubusercontent.com/5555882/203868776-56fe4d6d-7f19-49fa-a780-ee5b5c6e8c71.png)

**Comment by fmartinou** [comment]
Hi,

Even if you d'ont have any alarm, you have to set a PIN.
This PIN has to be a String so if you set it directly via the `yaml` descriptor, please wrap the value with quotes (ieg `'12345'`).

**Comment by agarridosaez** [comment]
Hi,

Perfecto. He hecho lo que me dijiste y ya está funcionando.
Muchísimas gracias
