### ISSUE TITLE
Preset modes

### ISSUE THREAD

**Issue by Philippe6256** [fmartinou/tydom2mqtt#60]
following an update, the AUTO preset mode seems to have disappeared? This mode existed previously and was very useful on the delta dore themostat

**Comment by fmartinou** [comment]
You're right, the mode has been removed in this commit
https://github.com/fmartinou/tydom2mqtt/commit/1790b4019c6187629f1c6c03932575ca2855dd8a

@gus8313, can you please explain why when you fixed the hold mode, you also chose to remove the AUTO?

**Comment by gus8313** [comment]
Oups, my bad, i thought it wasn’t used.
I fix it now

**Comment by fmartinou** [comment]
Thank you very much 👍!

**Comment by Philippe6256** [comment]
Congratulations on your responsiveness. Nice work.

**Comment by fmartinou** [comment]
It's merged (https://github.com/fmartinou/tydom2mqtt/pull/61)

=> I gonna release the fix.

**Comment by fmartinou** [comment]
The fix is available in the latest `2.6.5`.
