### ISSUE TITLE
Tydom2mqtt doesn't start on last version

### ISSUE THREAD

**Issue by cob94440** [fmartinou/tydom2mqtt#62]
L'addon ne démarre plus. le journal ne s'affiche pas. Comment revenir a la version précédente?

**Comment by cob94440** [comment]
Failed to to call /addons/6b64d821_tydom2mqtt/stats - 404 Client Error for http+docker://localhost/v1.41/containers/addon_6b64d821_tydom2mqtt/json: Not Found ("No such container: addon_6b64d821_tydom2mqtt")
J'ai cette erreur dans le log ha pourtant le container est bien présent

**Comment by cob94440** [comment]
Enfin des logs dans l'addon :
`Traceback (most recent call last):
  File "/app/main.py", line 226, in <module>
    loop_task()
  File "/app/main.py", line 148, in loop_task
    loop.run_until_complete(listen_tydom_forever(tydom_client))
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/main.py", line 160, in listen_tydom_forever
    await tydom_client.connect()
  File "/app/tydomConnector.py", line 109, in connect
    conn.request(
  File "/usr/local/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)`

**Comment by cob94440** [comment]
malgré suppression et réinstallation le problème persistait. J'ai du mettre l'adresse mediation au lieu de mon IP. Et c'est reparti

**Comment by everlink033** [comment]
> malgré suppression et réinstallation le problème persistait. J'ai du mettre l'adresse mediation au lieu de mon IP. Et c'est reparti

idem le module ne veut pas démarrer. Qu'appel tu adresse mediation?

**Comment by cob94440** [comment]
C'est l'adresse qui est noté dans le champ adresse du tydom

Le mer. 30 nov. 2022, 22:23, everlink033 ***@***.***> a
écrit :

**Comment by fmartinou** [comment]
I can reproduce your issue but I don't know yet what causes the regression.

The commits between the `2.6.4` and the `2.6.5` are unlikely the cause of the regression on SSL 🤔 
- https://github.com/fmartinou/tydom2mqtt/commit/ab7c69c3f3f0583b31cd4420d8e3ccf0584dc512
- https://github.com/fmartinou/tydom2mqtt/commit/75510879634c5eae5210390ce310e706104c5e50

**Comment by fmartinou** [comment]
The python image used to run the code has been updated 21 hours ago.

![image](https://user-images.githubusercontent.com/16061231/204921217-c08a2f69-052b-41d1-ad7e-f083c25850e9.png)

It may have an impact

**Comment by fmartinou** [comment]
The python image has probably be updated 21 hours ago from alpine 3.16 to alpine 3.17
![image](https://user-images.githubusercontent.com/16061231/204921793-8a50138b-65b1-45e1-a33f-2990e67f4de9.png)

**Comment by fmartinou** [comment]
I'll try to downgrade it to see if it fixes the issue.

**Comment by fmartinou** [comment]
Downgrading to alpine `3.16` fixes the issue.

I presume that some old unsecured SSL ciphers have been removed/disabled from the new Alpine version whereas Tydom is still using it for local communication.

**Comment by fmartinou** [comment]
Fixed version `2.6.6` is available.

**Comment by fmartinou** [comment]
Let me know if you still encounter issues.
++

**Comment by cob94440** [comment]
C'est ok pour moi mêm eavec l'ip du tydom
