### ISSUE TITLE
Support for tydom username & password login

### ISSUE THREAD

**Issue by tjamet** [fmartinou/tydom2mqtt#63]
Hi!

As envisioned in the FAQ, the new versions of Tydom uses some cloud login with an account to retrieve the site list and log to them.

Would it be an interesting feature to have in this utility?

Happy to contribute it!

**Comment by CyrilP** [comment]
Hi, 
I wrote some code to get the tydom password from cloud :
https://gist.github.com/CyrilP/379958e31ac4a4d167bb580e9c3225e1

maybe we should loop through the differents "sites" to find the one with the correct MAC in case someone has multiple tydom gateways

**Comment by CyrilP** [comment]
PR is ready

**Comment by tjamet** [comment]
I did write my own, but pushed it to a docker image only: https://hub.docker.com/layers/tjamet/tydom2mqtt/latest/images/sha256-45b1f9c97174d0b156c3882fcfe2a5cd9b8411a01a982cbe9909cb25e0f0f660?context=explore

Happy to contribute it if this is an interesting feature :D

**Comment by tjamet** [comment]
closing as this was implemented by #99
