### ISSUE TITLE
Porte de garage

### ISSUE THREAD

**Issue by Damien-root** [fmartinou/tydom2mqtt#7]
Bonjour,

je rencontre des difficultés avec une porte de garage, celle ci est bien détectée avec la création d'un switch mais aucune actions ou remontée d'informations ne s'effectuent. 
Les portes de garage sont elles gérées?

merci d'avance pour votre retour.

informations :

Product garage_door 1 (switch.product_garage_door_1)
MQTT discovery data:
Topic: homeassistant/switch/tydom/3_0/config
Payload
name: Product garage_door 1
unique_id: '3_0'
command_topic: switch/tydom/3_0/set_levelCmdGate
state_topic: switch/tydom/3_0/state
json_attributes_topic: switch/tydom/3_0/attributes
payload_on: TOGGLE
payload_off: TOGGLE
retain: 'false'
device:
  manufacturer: Delta Dore
  model: Porte
  name: Product garage_door 1
  identifiers: '3_0'
platform: mqtt
Subscribed topics:
switch/tydom/3_0/attributes
0 dernier(s) message(s) reçu(s)
switch/tydom/3_0/state
0 dernier(s) message(s) reçu(s)

device_id_tydom__Product_garage_door_1 (sensor.device_id_tydom_product_garage_door_1)
MQTT discovery data:
Topic: homeassistant/sensor/tydom/device_id_tydom_3_0/config
Payload
name: device_id_tydom__Product_garage_door_1
unique_id: device_id_tydom_3_0
device:
  manufacturer: Delta Dore
  model: Sensor
  name: device_id_tydom__Product_garage_door_1
  identifiers: 3_0_sensors
state_topic: sensor/tydom/device_id_tydom_3_0/state
platform: mqtt
Subscribed topics:
sensor/tydom/device_id_tydom_3_0/state
1 dernier(s) message(s) reçu(s)
Received 22:35:27
QoS: 0
Payload: 3
endpoint_id_tydom__Product_garage_door_1 (sensor.endpoint_id_tydom_product_garage_door_1)
MQTT discovery data:
Topic: homeassistant/sensor/tydom/endpoint_id_tydom_3_0/config
Payload
name: endpoint_id_tydom__Product_garage_door_1
unique_id: endpoint_id_tydom_3_0
device:
  manufacturer: Delta Dore
  model: Sensor
  name: endpoint_id_tydom__Product_garage_door_1
  identifiers: 3_0_sensors
state_topic: sensor/tydom/endpoint_id_tydom_3_0/state
platform: mqtt
Subscribed topics:
sensor/tydom/endpoint_id_tydom_3_0/state
1 dernier(s) message(s) reçu(s)
Received 22:35:27
QoS: 0
Payload: 0
id_tydom__Product_garage_door_1 (sensor.id_tydom_product_garage_door_1)
MQTT discovery data:
Topic: homeassistant/sensor/tydom/id_tydom_3_0/config
Payload
name: id_tydom__Product_garage_door_1
unique_id: id_tydom_3_0
device:
  manufacturer: Delta Dore
  model: Sensor
  name: id_tydom__Product_garage_door_1
  identifiers: 3_0_sensors
state_topic: sensor/tydom/id_tydom_3_0/state
platform: mqtt
Subscribed topics:
sensor/tydom/id_tydom_3_0/state
1 dernier(s) message(s) reçu(s)
Received 22:35:27
QoS: 0
Payload: 3_0
thermicDefect_tydom__Product_garage_door_1 (binary_sensor.thermicdefect_tydom_product_garage_door_1)
MQTT discovery data:
Topic: homeassistant/binary_sensor/tydom/thermicdefect_tydom_3_0/config
Payload
name: thermicDefect_tydom__Product_garage_door_1
unique_id: thermicDefect_tydom_3_0
device:
  manufacturer: Delta Dore
  model: Sensor
  name: thermicDefect_tydom__Product_garage_door_1
  identifiers: 3_0_sensors
state_topic: binary_sensor/tydom/thermicDefect_tydom_3_0/state
platform: mqtt
Subscribed topics:
binary_sensor/tydom/thermicDefect_tydom_3_0/state
1 dernier(s) message(s) reçu(s)
Received 22:35:27
QoS: 0
Payload: False

**Comment by BlacKTM1190** [comment]
Hello
Surement trop tard... mais je me suis penché sur ma garagedoor et je te confirmes qu'elles sont gérées.
Je les commande mais je n'ai encore pas le retour d'etat... 
Je remonterai une issue à ce sujet, si necessaire, quand j'aurais creusé un peu plus.

Ceci dit, ton identifier `switch/tydom/3_0/` n'est pas courant... de quel carte/modele/reference DD il s'agit ?

**Comment by Damien-root** [comment]
Hello,
Merci pour ton retour, personnellement je n'arrive toujours pas à gérer ma garagedoor.
Pour information mon `switch/tydom/3_0/` est module Delta Dore X3D (S11561-00001) sur moteur SOMMER Base+

**Comment by BlacKTM1190** [comment]
Hello
J'ai quasiment la même carte.
La différence de référence (NFF13694 chez moi) est seulement sur les initiales du moteur sur lequel elle s'adapte (NovoFerm dans mon cas).
AMHA, tu dois avoir une erreur dans ton endpoint_id.
En règle générale, ils sont sur 10 chiffres voire plus et, si je ne m'abuse, endpoint_id = device_id.
Peut être passer en debug, à fortiori avec la denrière release incluant #11 
Pour info, mes logs pour la garagedoor à la suite du /refresh/all sans debug : 
`2022-01-26 20:03:56,951 - switch - ERROR - 'level'`
`2022-01-26 20:03:56,952 - sensors - INFO - Sensor created / updated : device_id_tydom__GarageDoor 1578333328`
`2022-01-26 20:03:56,953 - sensors - INFO - Sensor created / updated : endpoint_id_tydom__GarageDoor 1578333328`
`2022-01-26 20:03:56,953 - sensors - INFO - Sensor created / updated : id_tydom__GarageDoor 1578333328_1578333328`
`2022-01-26 20:03:56,955 - sensors - INFO - Binary sensor created / updated : thermicDefect_tydom__GarageDoor False`
`2022-01-26 20:03:56,955 - switch - INFO - Switch created / updated : GarageDoor 1578333328_1578333328 None`
La 1ère trace est surement une des clès pour mon soucis de retour d'état, mais c'est un autre sujet...

**Comment by Damien-root** [comment]
Hello 

Malheureusement je ne trouve rien dans les log avec debug activé ...
```
2022-01-30 22:03:15,886 - switch - ERROR - 'level'
2022-01-30 22:03:15,887 - sensors - INFO - Sensor created / updated : device_id_tydom__Product_garage_door_1 3
2022-01-30 22:03:15,888 - sensors - INFO - Sensor created / updated : endpoint_id_tydom__Product_garage_door_1 0
2022-01-30 22:03:15,889 - sensors - INFO - Sensor created / updated : id_tydom__Product_garage_door_1 3_0
2022-01-30 22:03:15,890 - sensors - INFO - Binary sensor created / updated : thermicDefect_tydom__Product_garage_door_1 False
2022-01-30 22:03:15,890 - switch - INFO - Switch created / updated : Product garage_door 1 3_0 None
```
étonnant, je n'ai pas les même info que toi !?

**Comment by NODRAP63** [comment]
Bonjour, 
Je rencontre la même difficulté avec ma porte de garage. Elle est identifiée comme un switch mais ne fait rien. C'est un module 871180 sur un moteur tubauto. 

Vous avez progressé de votre coté ?

**Comment by Damien-root** [comment]
Bonjour,

Malheureusement je n'ai pas trouvé de solution pour le moment, mais je suis toujours en recherche.
Je doit avouer, un peu ralenti par ce beau temps.

**Comment by mopi1402** [comment]
Bonjour,
je confirme qu'avec cette PR https://github.com/fmartinou/tydom2mqtt/pull/44 le detecteur de porte de garage fonctionne ;)

Hello,
I can confirm that with this PR https://github.com/fmartinou/tydom2mqtt/pull/44 the garage sensor is working ;)

2022-09-30 11:56:05,350 - sensors - INFO - Binary sensor created / updated : intrusionDetect_tydom__Garage ON
2022-09-30 11:56:05,359 - tydomMessagehandler - INFO - Incoming data parsed successfully !
2022-09-30 11:56:41,307 - sensors - INFO - Binary sensor created / updated : intrusionDetect_tydom__Garage OFF
2022-09-30 11:56:41,307 - tydomMessagehandler - INFO - Incoming data parsed successfully !
2022-09-30 11:56:57,344 - sensors - INFO - Binary sensor created / updated : intrusionDetect_tydom__Garage ON
2022-09-30 11:56:57,344 - tydomMessagehandler - INFO - Incoming data parsed successfully !
2022-09-30 11:57:05,385 - sensors - INFO - Binary sensor created / updated : intrusionDetect_tydom__Garage OFF

**Comment by fmartinou** [comment]
Released as `2.5.0`
