### ISSUE TITLE
Need to specify alarm code pin to set up addon

### ISSUE THREAD

**Issue by Chartreusito** [fmartinou/tydom2mqtt#79]
Hi,

Just did a fresh install of the hass.io add on on my Home Assistant OS. I'm using mosquitto add on.

There was a parsing error preventing the parameters i had set up in the configuration tab to be used.

Once i specified a random value for "alarm pin code", which is supposed to be optionnal and is by default hidden, there was no more parsing error and i was able to complete the install.

Either the add on documentation should specify to set an alarm pin code, or the parameter should be given a default value to prevent this parsing error ?

**Comment by fmartinou** [comment]
Hi,

This issue is around for far too long => I'm gonna fix it ^^.
