### ISSUE TITLE
Retain state after HASS restarts

### ISSUE THREAD

**Issue by webjib** [fmartinou/tydom2mqtt#91]
Every time I restart HASS, all my covers show a "Unknown" state. I can see in MQTT that devices are published with "retain: false" parameter, I guess that's why the stat is lost each time I restart.

Could it be possible to change to "retain: true" or at least create a user setting in order to customise this behavior?

Thanks!

**Comment by fmartinou** [comment]
Hi,

That's right; some sensors are published with `retain: False`, some others with `retain: True` 🤔 .

=>I changed to publish all mqtt messages with `retain: True`.

**Comment by fmartinou** [comment]
Released as `3.0.2`
